version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    volumes:
      - ./app:/app
    image: python:3.9  # You can choose the Python version you need
    working_dir: /code
    command: >
       sh -c "python -u ingestion.py"
    environment:
      - FINNHUB_TOKEN=${FINNHUB_TOKEN}
      - RATE_LIMIT=5
