name: Build and Push Docker image

on: push

jobs:
  build-container:
    name: buildcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      - name: Build and push Producer Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./data-ingestion/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/producer:latest, ${{ secrets.DOCKER_USERNAME }}/producer:${{ github.run_number }}

      - name: Build and push Consumer Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./consumer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/consumer:latest, ${{ secrets.DOCKER_USERNAME }}/consumer:${{ github.run_number }}
